config/routes.rb
Rails.application.routes.draw do
  root 'page#about'

  delete 'session', action: :destroy, controller: 'session', as: :sign_out
  get '/auth/github/callback', action: :create, controller: 'session'

  get 'privacy', action: :privacy, controller: 'page'
  get 'markdown_help', action: :markdown_help, controller: 'page'
  get 'about', action: :about, controller: 'page'
  resources :ideas
  resources :messages, only: [:new, :create, :edit, :update, :destroy]
  resources :repositories

  namespace :user do
    resources :subscriptions, only: [:create, :destroy]
  end

  resources :errors, only: :new

  if Rails.env.test? || Rails.env.development?
    get :test_flash, controller: 'tests'
    get :colors, controller: 'tests'
    get :test_unauthorized, controller: 'tests'
  end
end

app/models/repository.rb
class Repository < ApplicationRecord

  include RailsStateMachine::Model
  include DoesTextFilter[TextFilter]
  include DoesArchive

  mount_uploader :preview_image, ImageUploader

  belongs_to :user

  scope :default_order, -> { order('last_commit_at DESC NULLS LAST', :id) }
  scope :published, -> { where(state: 'published') }

  has_defaults(languages: [], last_commits_at: [])

  validates :owner, presence: true
  validates :name, presence: true, uniqueness: { scope: :owner }
  validates :preview_image, presence: true, if: :published?
  validates :delivery_model, presence: true, if: :published?
  validates :categories, presence: true, if: :published?
  validates :categories, format: { with: /\A(?:\w+, )*\w+\z/, allow_blank: true }

  has_many :messages, as: :parent, dependent: :destroy
  has_many :user_subscriptions, class_name: 'User::Subscription', as: :subscribable

  assignable_values_for :delivery_model, allow_blank: true do
    ['self_hosted', 'saas']
  end

  state_machine do
    state :draft, initial: true
    state :published
    state :rejected

    event :publish do
      transitions from: [:draft, :rejected], to: :published
    end

    event :reject do
      transitions from: [:published], to: :rejected
    end
  end

  def messages_with_default_order
    messages.order([created_at: :asc], :id)
  end

  def repository_url_preview
    return if owner.blank? || name.blank?

    "https://github.com/#{owner_and_name}"
  end

  def to_s
    owner_and_name
  end

  private

  def owner_and_name
    "#{owner}/#{name}"
  end

end

app/models/repository/form.rb
class Repository::Form < ActiveType::Record[Repository]
  REPOSITORY_URL_PATTERN = %r(\Ahttps://github\.com/(?<owner>[^/]+)/(?<name>[^/]+)).freeze

  attribute :repository_url, :string

  after_initialize :set_repository_url
  before_validation :split_repository_url
  before_validation :set_current_user

  validate :validate_repository_url

  private

  def set_repository_url
    self.repository_url = repository_url_preview
  end

  def split_repository_url
    return if repository_url.blank?
    self.owner = repository_url[REPOSITORY_URL_PATTERN, :owner]
    self.name = repository_url[REPOSITORY_URL_PATTERN, :name]
  end

  def set_current_user
    self.user = Power.current.user
  end

  def validate_repository_url
    return if owner.present? && name.present?

    errors.add(:repository_url, :invalid)
  end

end

app/models/repository/recent_changes_analyzer.rb
class Repository::RecentChangesAnalyzer

  THRESHOLD_FOR_DAYS = 1
  THRESHOLD_FOR_WEEKS = 7
  THRESHOLD_FOR_MONTHS = 30
  THRESHOLD_FOR_YEARS = 365

  attr_accessor :last_commits_at

  def initialize(repository)
    self.last_commits_at = repository.last_commits_at
  end

  def count_commits_for_the_last_day
    if commit_distance >= THRESHOLD_FOR_DAYS
      "#{counter[:day]} commits within the last day."
    else
      "More than #{counter[:day]} commits within the last day."
    end
  end

  def count_commits_for_the_last_week
    if commit_distance >= THRESHOLD_FOR_WEEKS
      "#{counter[:week]} commits within the last week."
    else
      "More than #{counter[:week]} commits within the last week."
    end
  end

  def count_commits_for_the_last_month
    if commit_distance >= THRESHOLD_FOR_MONTHS
      "#{counter[:month]} commits within the last month."
    else
      "More than #{counter[:month]} commits within the last month."
    end
  end

  def count_commits_for_the_last_year
    if commit_distance >= THRESHOLD_FOR_YEARS
      "#{counter[:year]} commits within the last year."
    else
      "More than #{counter[:year]} commits within the last year."
    end
  end

  private

  def counter
    @counter ||= begin
      counter = {
        day: 0,
        week: 0,
        month: 0,
        year: 0,
      }

      last_commits_at.each do |last_commit_at|
        days_passed = (Date.today - last_commit_at.to_date).to_i

        counter[:day] += 1 if days_passed < THRESHOLD_FOR_DAYS
        counter[:week] += 1 if days_passed < THRESHOLD_FOR_WEEKS
        counter[:month] += 1 if days_passed < THRESHOLD_FOR_MONTHS
        counter[:year] += 1 if days_passed < THRESHOLD_FOR_YEARS
      end

      counter
    end
  end

  # We only store the latest 100 commits, so we need to predict if there might be more commits
  def commit_distance
    @earliest_commit ||= (Date.today - last_commits_at.min.to_date).to_i
  end

end

app/models/repository/synchronizer.rb
class Repository::Synchronizer

  REPOSITORY_META_QUERY = Github::Client.parse <<-'GRAPHQL'
    query($owner: String!, $name: String!) {
      repository(owner: $owner, name: $name) {
        description
        createdAt
        homepageUrl
        stargazers {
          totalCount
        }
        watchers {
          totalCount
        }
        issues {
          totalCount
        }
        languages(first: 50) {
          nodes {
            name
          }
        }
        ref(qualifiedName: "master") {
          target {
            ... on Commit {
              history(first: 100) {
                edges {
                  node {
                    committedDate
                  }
                }
              }
            }
          }
        }
        licenseInfo {
          name
        }
      }
    }
  GRAPHQL

  def self.run
    Repository.active.find_each do |repository|
      new(repository).synchronize_repository
    end
  end

  def initialize(repository)
    self.repository = repository
  end

  def synchronize_repository
    raw_repository = fetch_result.data.repository

    if raw_repository.present?
      last_commits_at = raw_repository.ref&.target&.history&.edges&.map { |edge| edge.node&.committed_date } || []

      repository.update!(
        description: raw_repository.description,
        homepage_url: raw_repository.homepage_url,
        total_stars: raw_repository.stargazers&.total_count,
        total_watchers: raw_repository.watchers&.total_count,
        total_issues: raw_repository.issues&.total_count,
        first_commit_at: raw_repository.created_at,
        last_commit_at: last_commits_at.first,
        last_commits_at: last_commits_at,
        languages: raw_repository.languages&.nodes&.map(&:name) || [],
        licence: raw_repository.license_info&.name,
        last_synchronized_at: Time.now,
      )
    end
  end

  private

  attr_accessor :repository

  def fetch_result
    Github::Client.query(
      REPOSITORY_META_QUERY,
      variables: { owner: repository.owner, name: repository.name }
    )
  end

end

app/models/repository/text_filter.rb
class Repository::TextFilter

  include Minidusen::Filter

  filter :text do |scope, phrases|
    columns = [:name, :owner, :description]
    scope.where_like(columns => phrases)
  end

  filter :text do |scope, phrases|
    columns = [:name, :owner, :description]
    scope
      .where_like(columns => phrases)
      .or(scope.where(id: Message.where(parent_type: 'Repository').filtered(phrases.join(' ')).pluck(:parent_id)))
  end

end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController

  power crud: :repositories, as: :repository_scope

  def index
    load_repositories
  end

  def show
    load_repository
  end

  def new
    build_repository
  end

  def create
    build_repository
    save_repository
  end

  def edit
    load_repository
    build_repository
  end

  def update
    load_repository
    build_repository
    save_repository
  end

  def destroy
    load_repository
    @repository.archive!
    destroy_flash(@repository)
    redirect_to repositories_path
  end

  private

  def load_repositories
    @repositories = repository_scope
      .default_order
      .active
      .includes(:user_subscriptions)
      .paginate(page: params[:page])
      .filtered(params[:query])
      .to_a
  end

  def load_repository
    @repository ||= repository_scope.find(params[:id])
  end

  def build_repository
    @repository ||= repository_scope.new
    @repository = ActiveType.cast(@repository, Repository::Form)
    @repository.attributes = repository_params
  end

  def save_repository
    action = @repository.new_record? ? :new : :edit

    if @repository.save
      success_flash(@repository)
      redirect_to(@repository)
    else
      error_flash(@repository)
      render(action, status: :unprocessable_entity)
    end
  end

  def repository_params
    repository_params = params[:repository]
    return {} if repository_params.blank?

    repository_params.permit(current_power.permitted_repository_attributes)
  end

end

app/helpers/repository_helper.rb
module RepositoryHelper

  def repository_preview_image_alternative_text(repository)
    if repository.new_record?
      'Preview of the website for the new repository'
    else
      "Preview of the website for #{repository.name}"
    end
  end

end

app/views/repositories/_form.haml
= simple_form_for(@repository) do |form|
  .card
    .card-header
      - if @repository.new_record?
        New #{@repository.model_name.human}
      - else
        #{@repository.name}
    .card-body
      = form.input :repository_url, hint: 'Enter the URL of the Github repository e.g. https://github.com/github/ruby'
      - if current_power.updatable_repositories?
        - if form.object.preview_image.present?
          %div= image_tag(form.object.preview_image.small.url, alt: repository_preview_image_alternative_text(form.object))
        = form.input :preview_image
        = form.input :preview_image_cache, as: :hidden
        = form.input :delivery_model, collection: form.object.humanized_assignable_delivery_models, value_method: :value, label_method: :humanized
        = form.input :categories, hint: 'Enter a comma separated list with single words'

    .card-footer
      .d-flex
        .mr-auto
          - if @repository.persisted?
            = content_link_to 'Delete', repository_path(@repository), {method: :delete, 'up-confirm': 'Are you sure?', class: 'btn btn-outline-danger'}
        = content_link_to 'Cancel', cancel_path(@repository), class: 'btn btn-light', 'up-close': ''
        - if form.object.may_reject?
          = form.button :button, 'Reject', name: 'repository[state_event]', value: 'reject', class: 'btn btn-outline-primary ml-1'
        - if form.object.may_publish?
          = form.button :button, 'Publish', name: 'repository[state_event]', value: 'publish', class: 'btn btn-outline-primary ml-1'
        = form.submit 'Save', class: 'btn btn-primary ml-1'

app/views/repositories/edit.haml
= render 'repositories/form'

app/views/repositories/index.haml
.d-flex
  .flex-grow-1
    = render 'shared/filter'
  - if current_user.present?
    = modal_link_to "New #{Repository.model_name.human}", new_repository_path, class: 'btn btn-primary ml-2'

.results
  - if @repositories.present?
    - @repositories.each do |repository|
      .card.mt-3
        .card-header.d-flex
          = content_link_to(repository.name, repository, class: 'text-reset text-decoration-none stretched-link mr-auto')
          %small.align-self-center
            - if repository.first_commit_at.present? && repository.last_commit_at.present?
              #{format_date(repository.first_commit_at)} - #{format_date(repository.last_commit_at)}
              = bullet
            #{repository.user_subscriptions.count} subscriptions
        .card-body
          .row
            .col
              - if repository.preview_image.present?
                = image_tag(repository.preview_image.small.url, alt: repository_preview_image_alternative_text(repository))
            .col
              %dl
                %dt= Repository.human_attribute_name(:last_synchronized_at)
                %dd= format_date(repository.last_synchronized_at)

                %dt= Repository.human_attribute_name(:state)
                %dd= humanized_state(repository.state)
              %p= format_string(repository.description)

    = render 'shared/pagination', collection: @repositories
  - else
    = no_records_available do
      %span.text-muted We do not have any repositories yet. You can
      %span.font-weight-bold= help_link(new_repository_path)
      %span.text-muted to fill this gap.

app/views/repositories/new.haml
= render 'repositories/form'

app/views/repositories/show.haml
= content_link_to '← Back to list', repositories_path, class: 'btn btn-outline-primary'

.card.mt-3
  .card-header
    .d-flex
      %h3.mr-auto= @repository.name
      .align-self-center
        = render 'shared/subscription', record: @repository
        - if current_power.include_record?(:updatable, @repository)
          = modal_link_to 'Edit', edit_repository_path(@repository), class: 'btn btn-outline-secondary'
    %small
      Added by
      %strong= @repository.user.to_s
      #{time_ago_in_words(@repository.created_at)} ago
      = bullet
      #{@repository.user_subscriptions.count} subscriptions

  %ul.list-group.list-group-flush#list-items
    %li.list-group-item
      - if @repository.last_synchronized_at.blank?
        .alert.alert-info{role: 'alert'}
          %strong Notice:
          This #{Repository.model_name.human} does not show all information from Github, but it will be updated within the
          next few hours. Thanks for your patient!
      - if @repository.preview_image.present?
        = image_tag(@repository.preview_image.medium.url, class: 'img-thumbnail rounded mx-auto mb-4 mt-4 d-block', alt: repository_preview_image_alternative_text(@repository))
      %dl
        %dt= Repository.human_attribute_name(:state)
        %dd= humanized_state(@repository.state)

        %dt= Repository.human_attribute_name(:delivery_model)
        %dd= format_text(@repository.humanized_delivery_model)

        %dt= Repository.human_attribute_name(:categories)
        %dd= format_text(@repository.categories)

        %dt= Repository.human_attribute_name(:description)
        %dd= format_text(@repository.description)

        %dt= Repository.human_attribute_name(:repository_url)
        %dd= external_link_to @repository.repository_url_preview, @repository.repository_url_preview

        %dt Popularity
        %dd
          .row
            .col
              #{Repository.human_attribute_name(:total_stars)}: #{format_string(@repository.total_stars)}
            .col
              #{Repository.human_attribute_name(:total_watchers)}: #{format_string(@repository.total_watchers)}
            .col
              #{Repository.human_attribute_name(:total_issues)}: #{format_string(@repository.total_issues)}

        %dt= Repository.human_attribute_name(:languages)
        %dd= @repository.languages.join(', ').presence || ndash

        %dt= Repository.human_attribute_name(:homepage_url)
        %dd
          - if @repository.homepage_url.present?
            = external_link_to @repository.homepage_url, @repository.homepage_url
          - else
            = ndash

        %dt= Repository.human_attribute_name(:licence)
        %dd= format_string(@repository.licence)

        %dt= Repository.human_attribute_name(:user)
        %dd= external_link_to @repository.user.nickname, "https://github.com/#{@repository.user.nickname}"

        %dt Recent changes
        - if @repository.last_commits_at.present?
          %dd= Repository::RecentChangesAnalyzer.new(@repository).count_commits_for_the_last_day
          %dd= Repository::RecentChangesAnalyzer.new(@repository).count_commits_for_the_last_week
          %dd= Repository::RecentChangesAnalyzer.new(@repository).count_commits_for_the_last_month
          %dd= Repository::RecentChangesAnalyzer.new(@repository).count_commits_for_the_last_year
        - else
          %dd= ndash

    - @repository.messages_with_default_order.each do |message|
      %li.list-group-item
        .row
          .col-10
            %small
              %strong= message.user.to_s
              replied
              #{time_ago_in_words(message.created_at)} ago
            .mt-3= format_markdown(message.body)
          .col-2.d-flex
            .mr-auto
            %div
              - if current_power.include_record?(:updatable, message)
                = modal_link_to 'Edit', edit_message_path(message), class: 'btn btn-outline-secondary btn-sm'
    %li.list-group-item= render 'shared/message', record: @repository, reveal: '#list-items:after'