config/routes.rb
Rails.application.routes.draw do
  root 'page#about'

  delete 'session', action: :destroy, controller: 'session', as: :sign_out
  get '/auth/github/callback', action: :create, controller: 'session'

  get 'privacy', action: :privacy, controller: 'page'
  get 'markdown_help', action: :markdown_help, controller: 'page'
  get 'about', action: :about, controller: 'page'
  resources :ideas
  resources :messages, only: [:new, :create, :edit, :update, :destroy]
  resources :repositories

  namespace :user do
    resources :subscriptions, only: [:create, :destroy]
  end

  resources :errors, only: :new

  if Rails.env.test? || Rails.env.development?
    get :test_flash, controller: 'tests'
    get :colors, controller: 'tests'
    get :test_unauthorized, controller: 'tests'
  end
end

app/models/idea.rb
class Idea < ApplicationRecord

  include DoesTextFilter[TextFilter]

  belongs_to :user
  has_many :messages, as: :parent, dependent: :destroy
  has_many :user_subscriptions, class_name: 'User::Subscription', as: :subscribable

  scope :default_order, -> { order(created_at: :desc) }

  validates :title, :description, :body, presence: true

  def messages_with_default_order
    messages.order([created_at: :asc], :id)
  end

  def to_s
    title
  end
end

app/models/idea/text_filter.rb
class Idea::TextFilter

  include Minidusen::Filter

  filter :text do |scope, phrases|
    columns = [:title, :description, :body]
    scope
      .where_like(columns => phrases)
      .or(scope.where(id: Message.where(parent_type: 'Idea').filtered(phrases.join(' ')).pluck(:parent_id)))
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  power crud: :ideas, as: :idea_scope

  def index
    load_ideas
  end

  def show
    load_idea
  end

  def new
    build_idea
  end

  def create
    build_idea
    save_idea
  end

  def edit
    load_idea
    build_idea
  end

  def update
    load_idea
    build_idea
    save_idea
  end

  def destroy
    load_idea
    @idea.destroy!
    destroy_flash(@idea)
    redirect_to ideas_path
  end

  private

  def load_ideas
    @ideas = idea_scope
      .default_order
      .includes(:user_subscriptions)
      .paginate(page: params[:page])
      .filtered(params[:query])
      .to_a
  end

  def load_idea
    @idea ||= idea_scope
      .includes(:messages)
      .find(params[:id])
  end

  def build_idea
    @idea ||= idea_scope.new
    @idea.attributes = idea_params
  end

  def save_idea
    action = @idea.new_record? ? :new : :edit

    if @idea.save
      success_flash(@idea)
      redirect_to(@idea)
    else
      error_flash(@idea)
      render(action, status: :unprocessable_entity)
    end
  end

  def idea_params
    idea_params = params[:idea]
    return {} if idea_params.blank?

    idea_params.permit(:title, :description, :body)
  end

end

app/views/ideas/_form.haml
= simple_form_for(@idea) do |form|
  .card
    .card-header
      - if @idea.new_record?
        New #{Idea.model_name.human}
      - else
        #{@idea.title}
    .card-body
      = form.input :title
      = form.input :description
      = form.input :body, as: :markdown

    .card-footer
      .d-flex
        .mr-auto
          - if @idea.persisted?
            = content_link_to 'Delete', idea_path(@idea), method: :delete, 'up-confirm': 'Are you sure?', class: 'btn btn-outline-danger'
        = content_link_to 'Cancel', cancel_path(@idea), class: 'btn btn-light', 'up-close': ''
        = form.submit 'Save', class: 'btn btn-primary ml-1'

app/views/ideas/edit.haml
= render 'ideas/form'

app/views/ideas/index.haml
.d-flex
  .flex-grow-1
    = render 'shared/filter'
  - if current_user.present?
    = modal_link_to "New #{Idea.model_name.human}", new_idea_path, class: 'btn btn-primary ml-2'

.results
  - if @ideas.present?
    - @ideas.each do |idea|
      .card.mt-3
        .card-header.d-flex
          = content_link_to(idea.title, idea, class: 'text-reset text-decoration-none stretched-link mr-auto')
          %small.align-self-center
            #{idea.user_subscriptions.count} subscriptions
        .card-body
          %p.card-text= idea.description

    = render 'shared/pagination', collection: @ideas
  - else
    = no_records_available do
      %span.text-muted We do not have any ideas yet. You can
      %span.font-weight-bold= link_to('start a idea', new_idea_path)
      %span.text-muted at any time.

app/views/ideas/new.haml
= render 'ideas/form'

app/views/ideas/show.haml
= content_link_to '← Back to list', ideas_path, class: 'btn btn-outline-primary'

.card.mt-3
  .card-header
    .d-flex
      %h3.mr-auto= @idea.title
      .align-self-center
        = render 'shared/subscription', record: @idea
        - if current_power.include_record?(:updatable, @idea)
          = modal_link_to 'Edit', edit_idea_path(@idea), class: 'btn btn-outline-secondary'
    %small
      Created by
      %strong= @idea.user.to_s
      #{time_ago_in_words(@idea.created_at)} ago
      = bullet
      #{@idea.user_subscriptions.count} subscriptions

  %ul.list-group.list-group-flush#list-items
    %li.list-group-item
      = @idea.description
      %hr
      .mt-3= format_markdown(@idea.body)

    - @idea.messages_with_default_order.each do |message|
      %li.list-group-item
        .row
          .col-10
            %small
              %strong= message.user.to_s
              replied
              #{time_ago_in_words(message.created_at)} ago
            .mt-3= format_markdown(message.body)
          .col-2.d-flex
            .mr-auto
            %div
              - if current_power.include_record?(:updatable, message)
                = modal_link_to 'Edit', edit_message_path(message), class: 'btn btn-outline-secondary btn-sm'
    %li.list-group-item= render 'shared/message', record: @idea, reveal: '#list-items:after'