config/routes.rb
Rails.application.routes.draw do
  root 'page#about'

  delete 'session', action: :destroy, controller: 'session', as: :sign_out
  get '/auth/github/callback', action: :create, controller: 'session'

  get 'privacy', action: :privacy, controller: 'page'
  get 'markdown_help', action: :markdown_help, controller: 'page'
  get 'about', action: :about, controller: 'page'
  resources :ideas
  resources :messages, only: [:new, :create, :edit, :update, :destroy]
  resources :repositories

  namespace :user do
    resources :subscriptions, only: [:create, :destroy]
  end

  resources :errors, only: :new

  if Rails.env.test? || Rails.env.development?
    get :test_flash, controller: 'tests'
    get :colors, controller: 'tests'
    get :test_unauthorized, controller: 'tests'
  end
end

app/models/shared/does_archive.rb
module DoesArchive

  as_trait do
    scope :active, -> { where(archived_at: nil) }

    def archive
      update(archived_at: Time.now)
    end

    def archive!
      update!(archived_at: Time.now)
    end

    def archived?
      archived_at.present?
    end

    def restore
      update(archived_at: nil)
    end

    def restore!
      update!(archived_at: nil)
    end

    def active?
      archived_at.blank?
    end
  end

end

app/models/shared/does_find_by_anything.rb
module DoesFindByAnything

  as_trait do

    define_singleton_method(:find_by_anything) do |identifier|
      matchable_columns = columns.reject { |column| [:binary, :boolean].include?(column.type) }

      query_clauses = matchable_columns.map do |column|
        "CAST(#{table_name}.#{column.name} AS TEXT) = ?"
      end

      bindings = [identifier] * query_clauses.size
      where([query_clauses.join(' OR '), *bindings]).first
    end

    define_singleton_method(:find_by_anything!) do |identifier|
      find_by_anything(identifier) || raise(
        ActiveRecord::RecordNotFound,
        "No column equals #{identifier.inspect}"
      )
    end

  end

end

app/models/shared/does_text_filter.rb
module DoesTextFilter

  as_trait do |filter_class|

    define_singleton_method(:filtered) do |query|
      query.present? ? filter_class.new.filter(self, query) : all
    end

  end

end

app/views/shared/_filter.haml
= form_with(url: request.path, method: :get, html: {class: 'form-inline', 'up-target' => '.results', 'up-autosubmit' => '', 'up-reveal' => 'false'}) do |form|
  = form.spec_label :query
  = form.text_field :query, value: params[:query], class: 'form-control flex-fill'
  = form.submit 'Search', class: 'btn btn-secondary ml-2'

app/views/shared/_message.haml
- if current_user.present?
  = render 'messages/form_for_new', message: record.messages.build, reveal: reveal

app/views/shared/_pagination.haml
.mt-3
  .sr-only Showing page #{collection.current_page.to_i} of #{collection.total_pages.to_i}
  = will_paginate(collection)

app/views/shared/_subscription.haml
- if signed_in?
  - subscription = User::Subscription.find_or_initialize_by(user: current_user, subscribable: record)
  - if subscription.new_record?
    = simple_form_for(subscription, html: {class: 'd-inline'}) do |form|
      = form.input :subscribable_id, wrapper_html: {class: 'mb-0'}, as: :hidden
      = form.input :subscribable_type, wrapper_html: {class: 'mb-0'}, as: :hidden
      = form.submit 'Subscribe', class: 'btn btn-outline-secondary'
  - else
    = content_link_to 'Unsubscribe', user_subscription_path(subscription), method: :delete, 'up-confirm': 'Are you sure?', class: 'btn btn-outline-secondary'