config/routes.rb
Rails.application.routes.draw do
  root 'page#about'

  delete 'session', action: :destroy, controller: 'session', as: :sign_out
  get '/auth/github/callback', action: :create, controller: 'session'

  get 'privacy', action: :privacy, controller: 'page'
  get 'markdown_help', action: :markdown_help, controller: 'page'
  get 'about', action: :about, controller: 'page'
  resources :ideas
  resources :messages, only: [:new, :create, :edit, :update, :destroy]
  resources :repositories

  namespace :user do
    resources :subscriptions, only: [:create, :destroy]
  end

  resources :errors, only: :new

  if Rails.env.test? || Rails.env.development?
    get :test_flash, controller: 'tests'
    get :colors, controller: 'tests'
    get :test_unauthorized, controller: 'tests'
  end
end

app/views/layouts/_favicons.haml
%link{href: asset_pack_path('media/images/favicons/apple-icon-57x57.png'), rel: 'apple-touch-icon', sizes: '57x57'}
%link{href: asset_pack_path('media/images/favicons/apple-icon-60x60.png'), rel: 'apple-touch-icon', sizes: '60x60'}
%link{href: asset_pack_path('media/images/favicons/apple-icon-72x72.png'), rel: 'apple-touch-icon', sizes: '72x72'}
%link{href: asset_pack_path('media/images/favicons/apple-icon-76x76.png'), rel: 'apple-touch-icon', sizes: '76x76'}
%link{href: asset_pack_path('media/images/favicons/apple-icon-114x114.png'), rel: 'apple-touch-icon', sizes: '114x114'}
%link{href: asset_pack_path('media/images/favicons/apple-icon-120x120.png'), rel: 'apple-touch-icon', sizes: '120x120'}
%link{href: asset_pack_path('media/images/favicons/apple-icon-144x144.png'), rel: 'apple-touch-icon', sizes: '144x144'}
%link{href: asset_pack_path('media/images/favicons/apple-icon-152x152.png'), rel: 'apple-touch-icon', sizes: '152x152'}
%link{href: asset_pack_path('media/images/favicons/apple-icon-180x180.png'), rel: 'apple-touch-icon', sizes: '180x180'}
%link{href: asset_pack_path('media/images/favicons/android-icon-192x192.png'), rel: 'icon', sizes: '192x192', type: 'image/png'}
%link{href: asset_pack_path('media/images/favicons/favicon-32x32.png'), rel: 'icon', sizes: '32x32', type: 'image/png'}
%link{href: asset_pack_path('media/images/favicons/favicon-96x96.png'), rel: 'icon', sizes: '96x96', type: 'image/png'}
%link{href: asset_pack_path('media/images/favicons/favicon-16x16.png'), rel: 'icon', sizes: '16x16', type: 'image/png'}

app/views/layouts/_flashes.haml
- flash_mapping = {'success' => 'success', 'error' => 'danger'}
.alerts(up-hungry)
  - flash.each do |level, message|
    %div{class: "alert alert-#{flash_mapping.fetch(level)}"}
      = message
      %button(type='button' class='close' aria-label='Close')
        %span(aria-hidden) ×

app/views/layouts/_footer.haml
.footer.mt-auto.py-3.bg-light
  .container
    .nav.justify-content-end
      %li.nav-item
        = content_link_to 'About', about_path, class: 'nav-link'
      %li.nav-item
        = content_link_to 'Privacy', privacy_path, class: 'nav-link'

app/views/layouts/_navigation.haml
.navbar.fixed-top.navbar-light.bg-light.navbar-expand-lg
  .container
    = content_link_to root_path, class: 'navbar-brand' do
      = image_pack_tag 'media/images/wintermute-transparent.png', alt: 'Wintermute Logo', height: 30, class: 'mr-1'
      Wintermute
    %button.navbar-toggler(aria-controls='collapsable_navigation' aria-expanded='false' aria-label='Toggle navigation' type='button' data-collapsable-navigation up-data='{"target": "collapsable_navigation"}')
      %span.navbar-toggler-icon
    #collapsable_navigation.collapse.navbar-collapse
      %ul.navbar-nav(up-nav)
        %li.nav-item
          = content_link_to 'Evaluate', ideas_path, class: 'nav-link', :'up-alias' => "#{ideas_path}/* #{ideas_path}?*"
        %li.nav-item
          = content_link_to 'Explore', repositories_path, class: 'nav-link', :'up-alias' => "#{repositories_path}/* #{repositories_path}?*"
      %ul.navbar-nav.ml-auto
        %li.nav-item
          - if signed_in?
            = link_to 'Sign out', sign_out_path, method: :delete, class: 'nav-link'
          - else
            = sign_in_link('Sign in', class: 'nav-link')

app/views/layouts/application.haml
!!!
%html{lang: I18n.locale, class: 'h-100'}

  %head
    %meta(charset='utf-8')
    %meta(http-equiv='x-ua-compatible' content='ie=edge')
    %meta(name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no')
    %meta(name='description' content='Wintermute should help programmers to create new web applications that can become more than just a side project. And help to explore already existing projects.')

    = render 'layouts/favicons'

    = csrf_meta_tags

    %title
      Wintermute

    = stylesheet_pack_tag 'application'

  %body{data: {env: Rails.env}, class: 'd-flex flex-column h-100'}
    .flex-shrink-0
      .container.mb-5
        = render 'layouts/navigation'

        .page-target
          .modal-target
            = render 'layouts/flashes'
            = yield
    = render 'layouts/footer'
    // https://makandracards.com/makandra/17349-speed-up-your-websites-put-javascripts-at-bottom
    = javascript_pack_tag 'application'

app/views/layouts/application.html.haml
!!!
%html{ lang: I18n.locale }

  %head
    %meta(charset='utf-8')
    %meta(http-equiv='x-ua-compatible' content='ie=edge')
    %meta(name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no')

    = csrf_meta_tags

    %title
      Wintermute

    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'

  %body{ data: {env: Rails.env} }

    .container
      = render 'layouts/flashes'

      .content
        = yield